version: '3'
services:
   jenkins:
      image: jenkins/jenkins
      container_name: jenkins
      privileged: true
      user: jenkins
      restart: always
      ports:
         - 8080:8080
         - 50000:50000
      volumes:
         - /root/Docker-jenkins/data/jenkins_home:/var/jenkins_home
         - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #     - VIRTUAL_HOST=jenkins.thanhtha.name.vn
    #     - LETSENCRYPT_HOST=jenkins.thanhtha.name.vn
    #     - LETSENCRYPT_EMAIL=letha01685022@gmail.com
    
   proxy:
      image: nginx
      container_name: nginx-proxy
      user: root
      restart: always
      ports:
         - 80:80
         - 443:443
      volumes:
         - /root/Docker-jenkins/data/nginx/conf.d:/etc/nginx/conf.d
         - /root/Docker-jenkins/data/nginx/logs:/var/log/nginx
         - /root/Docker-jenkins/data/certbot/www/:/var/www/certbot
         - /root/Docker-jenkins/data/certbot/conf/:/etc/letsencrypt
         - /root/Docker-jenkins/data/certbot/var:/var/lib/letsencrypt
         - /var/run/docker.sock:/tmp/docker.sock

   certbot:
      container_name: certbot
      image: certbot/certbot:latest
      volumes:
         - /root/Docker-jenkins/data/certbot/conf/:/etc/letsencrypt
         - /root/Docker-jenkins/data/certbot/var:/var/lib/letsencrypt
         - /root/Docker-jenkins/data/certbot/www/:/var/www/certbot
         - /var/run/docker.sock:/tmp/docker.sock
      command: certonly --webroot --webroot-path=/var/www/certbot --email letha01685022@gmail.com --agree-tos --no-eff-email -d jenkins.thanhtha.name.vn
      depends_on:
         - proxy