version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - /data/monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/monitor/prometheus/prom_data:/prometheus

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    user: root
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_PATHS_CONFIG="/etc/grafana/grafana.ini"
    volumes:
      - /data/monitor/garafana/provisioning/:/etc/grafana/provisioning/datasources
      - /data/monitor/garafana/data/:/var/lib/grafana
    restart: unless-stopped

  proxy:
      image: nginx
      container_name: nginx-proxy
      user: root
      restart: always
      ports:
         - 80:80
         - 443:443
      volumes:
         - /data/monitor/nginx/conf.d:/etc/nginx/conf.d
         - /data/monitor/certbot/www/:/var/www/certbot
         - /data/monitor/certbot/conf/:/etc/letsencrypt
         - /data/monitor/certbot/var:/var/lib/letsencrypt
         - /var/run/docker.sock:/tmp/docker.sock

  certbot:
      container_name: certbot
      image: certbot/certbot:latest
      volumes:
         - /data/monitor/certbot/conf/:/etc/letsencrypt
         - /data/monitor/certbot/var:/var/lib/letsencrypt
         - /data/monitor/certbot/www/:/var/www/certbot
         - /var/run/docker.sock:/tmp/docker.sock
      command: certonly --webroot --webroot-path=/var/www/certbot --email letha01685022@gmail.com --agree-tos --no-eff-email --force-renewal -d prometheus.thanhtha.name.vn -d garafana.thanhtha.name.vn
      depends_on:
         - proxy
    